# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    filter_sets:
        cache: ~

        # the name of the "filter set"
        xs_thumb:
            quality: 85
            filters:
                downscale:
                    by: 0.8


        medium_thumb:

            # adjust the image quality to 75%
            quality: 85
            cache: default

            # list of transformations to apply (the "filters")
            filters:
                scale:
                    dim: [ 252, 227 ]
        large_thumb:

            # adjust the image quality to 75%
            quality: 85

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [461, 534], mode: outbound }